model:
  type: inf-llm
  path: NousResearch/Meta-Llama-3.1-8B-Instruct
  block_size: 128
  fattn: false
  n_init: 64
  n_local: 64
  topk: 4
  repr_topk: 4
  max_cached_block: 32
  exc_block_size: 64
  base: 500000
  distance_scale: 1.0

max_len: 2147483647
chunk_size: 8192
conv_type: llama-3-inst